# Generated by Django 2.2.4 on 2020-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniTracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
