# Generated by Django 2.2.4 on 2020-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniTracking', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='workingpresently',
            field=models.CharField(max_length=10),
        ),
    ]
