# Generated by Django 2.2.4 on 2020-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniTracking', '0004_auto_20200221_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_name', models.CharField(max_length=200)),
                ('announcement_description', models.CharField(max_length=500)),
                ('adding_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
