# Generated by Django 2.2.4 on 2020-02-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branchclass',
            new_name='branchandclass',
        ),
    ]
