# Generated by Django 2.2.4 on 2020-02-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20200215_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branchandclass',
        ),
    ]
