# Generated by Django 2.2.4 on 2020-02-15 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0004_branchclass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branchclass',
            table='branchclass',
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactnumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.branchclass')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
