# Generated by Django 2.2.4 on 2020-02-15 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0005_auto_20200215_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classteacher', models.CharField(default='None', max_length=50)),
                ('contactnumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('authorityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authority',
            },
        ),
    ]
