# Generated by Django 2.2.4 on 2020-03-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='classteacher',
        ),
    ]
